/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdbool.h>

#include <stm32f4xx.h>
#include <mcalGPIO.h>



int main(void)
{
	__disable_irq();
	gpioInitPort(GPIOA);
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	gpioSelectPinMode(GPIOA,PIN0,INPUT);
	gpioSelectPinMode(GPIOA,PIN4,OUTPUT);
	GPIOA->OTYPER &= ~(GPIO_OTYPER_OT0 | GPIO_OTYPER_OT4);
	GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPD0 | GPIO_PUPDR_PUPD4);
	SYSCFG->EXTICR[0] &= ~0x000F;
	EXTI->IMR |= EXTI_IMR_IM0;
	EXTI->FTSR |= EXTI_FTSR_TR0;
	NVIC_EnableIRQ(EXTI0_IRQn);
	__enable_irq();
    while (1)
    {
    	;
    }
}

void EXTI0_IRQHandler(void)
{
	gpioTogglePin(GPIOA,PIN4);
	EXTI->PR |= EXTI_PR_PR0;
}


